GET http://localhost:8080/api/v1/commentMenu
GET http://localhost:8080/api/v1/commentMenu/1

###

###
POST http://localhost:8080/api/v1/commentMenu
Content-Type: application/json

{
    "user_id": "67d55a495855da0f023dd8e2",
    "menu_id": "67da3d4109e0c016e629dce1",
    "content": "his his ",
    "likeCount": 1000,
    "dislikeCount": 0
}

###

PUT http://localhost:8080/api/v1/users/67d16d9c5fa5d8164fc7c6aa
Content-Type: application/json

{
    "username": "khachhang",
    "fullname": "khachhang",
    "email": "khachhang@gmail.com",
    "password": "khachhang",
    "role": "restaurant_owner"
}

###
DELETE http://localhost:8080/api/v1/users/67d2491bcec58d464bf67774

###
