GET http://localhost:8080/api/v1/restaurants
###
POST http://localhost:8080/api/v1/restaurants
Content-Type: application/json

{
    "owner_id": "67d16d07fa72b74e7f894d72",
    "name": "Nhà hàng Mikodangiu",
    "address": "123 Nguyễn Văn Linh",
    "phone": "0909090909",
    "description": "Nhà hàng ngon",
    "category_id": "67d2cbb1b3985423bcdcf188",
    "average_rating": 4.5,
    "image_url": "https://via.placeholder.com/150",
    "is_active": true
}

###
PUT http://localhost:8080/api/v1/restaurants/67d16d9c5fa5d8164fc7c6aa
Content-Type: application/json

{
    "name": "Updated Restaurant Name",
    "address": "Updated Address",
    "phone": "Updated Phone"
}

###
DELETE http://localhost:8080/api/v1/restaurants/67d2491bcec58d464bf67774

###
